package:
    type:           project
    name:           chkipper
    title:          Changelog keeper
    keywords:       commits, semver, changelog, chkipper
    namespace:      hiqdev\chkipper
    description:    |
        Helps to track all the commits to your project and convert them to CHANGELOG file.

        Features:

        - fills `history.md` from git commits history
        - converts `history.md` to `CHANGELOG.md`
        - creates links to commits
        - provides bump to version command

        Todo:

        - create links to github users and version diffs
        - colorized output, notify changed files
